#!/bin/bash

echo "🔧 Purging Cloudflare Cache..."
echo ""
echo "To purge Cloudflare cache, you need to:"
echo ""
echo "1. Go to Cloudflare Dashboard: https://dash.cloudflare.com"
echo "2. Select your domain: memelaunchtycoon.com"
echo "3. Go to 'Caching' → 'Configuration'"
echo "4. Click 'Purge Everything' button"
echo ""
echo "OR use the Cloudflare API:"
echo ""
echo "curl -X POST \"https://api.cloudflare.com/client/v4/zones/YOUR_ZONE_ID/purge_cache\" \\"
echo "  -H \"Authorization: Bearer YOUR_API_TOKEN\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  --data '{\"purge_everything\":true}'"
echo ""
echo "Alternative: Purge specific URLs:"
echo "curl -X POST \"https://api.cloudflare.com/client/v4/zones/YOUR_ZONE_ID/purge_cache\" \\"
echo "  -H \"Authorization: Bearer YOUR_API_TOKEN\" \\"
echo "  -H \"Content-Type: application/json\" \\"
echo "  --data '{\"files\":[\"https://memelaunchtycoon.com/\"]}'"
echo ""
echo "✅ After purging cache, users will see the new version immediately!"
